const fs = require('fs');
const dicPath = 'F:/trincado/public/data/diccionario_sinapsis.json';
let dic = JSON.parse(fs.readFileSync(dicPath, 'utf8'));

// BLOQUE 2: Identidades, figuras y conceptos histórico-doctrinales
Object.assign(dic, {
  "Magnetismo Espiritual": { "Definición": "La sustancia única de la que está hecho el Universo. Todo — gravedad, amor, pensamiento, vida — es magnetismo espiritual en diferentes frecuencias. No es metáfora: es la realidad física-metafísica que la ciencia descubrirá completamente.", "Conexiones": ["Sustancia Única","Desdoblamiento","Método Supremo","Todo es Magnetismo"], "Obras": ["El Magnetismo en su Origen","Filosofía Austera Racional","Los Extremos se Tocan"] },
  "Sustancia Única": { "Definición": "El principio de que existe una sola sustancia en el Universo — el Magnetismo Espiritual — que se manifiesta en diferentes estados y frecuencias. No hay dualismo materia/espíritu: son la misma sustancia en diferentes densidades.", "Conexiones": ["Magnetismo Espiritual","Todo es Magnetismo","Universo Solidarizado"], "Obras": ["El Magnetismo en su Origen","Filosofía Austera Racional"] },
  "Todo es Magnetismo": { "Definición": "La proclama que sintetiza toda la ontología de Trincado: 'Todo es Magnetismo Espiritual'. Aparece al final de múltiples obras como el teorema que todos los desarrollos doctrinales demuestran.", "Conexiones": ["Magnetismo Espiritual","Sustancia Única","Proclama Final"], "Obras": ["El Magnetismo en su Origen","Los Extremos se Tocan"] },
  "Universo Solidarizado": { "Definición": "El estado del Universo tal como es en su realidad: todos los seres están interconectados bajo la misma ley y la misma sustancia. La división y la competencia son ilusiones del error — la solidaridad es la realidad.", "Conexiones": ["Sustancia Única","Mundo Comunizado","Solidaridad Universal"], "Obras": ["Los Extremos se Tocan","El Magnetismo en su Origen"] },
  "Mundo Comunizado": { "Definición": "El estado social que corresponde a la realidad espiritual del Universo Solidarizado. No es el comunismo ateo de Marx — es la organización social bajo la Ley de Amor, donde Eloí es el único propietario y todos son herederos.", "Conexiones": ["Universo Solidarizado","Eloí","Comuna Universal","Comunismo Racional"], "Obras": ["Los Extremos se Tocan","Código de Amor Universal"] },
  "Proclama Final": { "Definición": "La síntesis doctrinal que cierra múltiples obras de Trincado: 'El Universo, solidarizado. El Mundo todo, comunizado. La ley es una. La substancia una. Uno es el principio. Uno es el fin. Todo es Magnetismo Espiritual.'", "Conexiones": ["Universo Solidarizado","Mundo Comunizado","Sustancia Única","Todo es Magnetismo"], "Obras": ["Los Extremos se Tocan","El Magnetismo en su Origen"] },
  "Escuela Magnetológica": { "Definición": "La Escuela Magnético-Espiritual de la Comuna Universal — la institución fundada por Trincado para la enseñanza libre de la doctrina racional. No es una religión, no tiene sacerdotes, no tiene rituales. Es el espacio de estudio soberano.", "Conexiones": ["Ciudad Invisible","Enseñanza Racional","Escuela","Continuidad Misionera"], "Obras": ["Los Extremos se Tocan","Código de Amor Universal"] },
  "Ciudad Invisible": { "Definición": "El nombre que Trincado da a la Escuela como comunidad espiritual sin fronteras geográficas. Existe donde existe un estudiante honrado que busca la verdad. No tiene sede física porque la verdad no necesita edificio.", "Conexiones": ["Escuela Magnetológica","Escuela","Enseñanza sin Dogma"], "Obras": ["Código de Amor Universal"] },
  "Padre Universal": { "Definición": "El Padre Hellí — la Causa Primera que todo lo crea y sustenta. No el dios vengativo de las religiones, sino la Inteligencia-Amor que opera a través de sus leyes. Se conoce estudiándolo, no rezándole.", "Conexiones": ["Hellí","Eloí","Causa Primera","Anti-Dios Comercial"], "Obras": ["Buscando a Dios","Los Cinco Amores"] },
  "Anti-Dios Comercial": { "Definición": "La denuncia de Trincado contra el dios inventado por las religiones para hacer negocios: el dios que castiga, que necesita templos, que cobra diezmos, que vende indulgencias. No tiene nada que ver con Hellí.", "Conexiones": ["Hellí","Ramera","Concupiscencia Religiosa","Papado"], "Obras": ["Buscando a Dios","Primer Rayo de Luz"] },
  "Ramera": { "Definición": "El nombre que Trincado da al sistema religioso (especialmente el católico romano) que ha prostituido la verdad espiritual convirtiéndola en negocio de poder. Tomado del Apocalipsis: 'La Gran Ramera de Babilonia'.", "Conexiones": ["Papado","Bestia 666","Ramera de Babilonia","Concupiscencia Religiosa"], "Obras": ["Buscando a Dios","Primer Rayo de Luz","Los Extremos se Tocan"] },
  "Ramera de Babilonia": { "Definición": "La identificación del sistema religioso de poder (Roma, el Vaticano) con la 'Gran Ramera' del Apocalipsis. No es un insulto emocional — es un diagnóstico histórico: una institución que vende la verdad al mejor postor.", "Conexiones": ["Ramera","Papado","Bestia 666","Apocalipsis Racional"], "Obras": ["Buscando a Dios","Primer Rayo de Luz"] },
  "Papado": { "Definición": "La institución del papado romano, identificada por Trincado como el principal agente de adulteración de la verdad espiritual. Desde Constantino hasta hoy, el papado ha usado la religión como instrumento de poder político y económico.", "Conexiones": ["Ramera","Constantino","Bestia 666","Dominio del Dogma"], "Obras": ["Los Extremos se Tocan","Primer Rayo de Luz"] },
  "Constantino": { "Definición": "El emperador romano que convirtió el cristianismo en religión de estado (313 d.C.) no por fe sino por necesidad política. Con Constantino nace la Iglesia Católica como instrumento de poder — la traición a Jesús institucionalizada.", "Conexiones": ["Papado","Traición a Jesús","Historia Misionera","Adulteración Histórica"], "Obras": ["Los Extremos se Tocan"] },
  "Traición a Jesús": { "Definición": "El proceso histórico por el que el mensaje de Jesús ('Ama a tu hermano') fue convertido en dogma religioso de control. El principal traidor no fue Judas — fue el concilio de Nicea que fabricó la teología del Cristo-Dios.", "Conexiones": ["Constantino","Jesús Histórico","Anti-Deificación","Ramera"], "Obras": ["Los Extremos se Tocan","Buscando a Dios"] },
  "Adulteración Histórica": { "Definición": "El proceso sistemático por el que las verdades doctrinales fueron mezcladas con intereses de poder en cada etapa histórica. Trincado traza este proceso desde Adán hasta el siglo XX.", "Conexiones": ["Historia Misionera","Constantino","Papado","Origen de las Religiones"], "Obras": ["Los Extremos se Tocan","Primer Rayo de Luz"] }
});

fs.writeFileSync(dicPath, JSON.stringify(dic, null, 2), 'utf8');
console.log('Bloque 2 completado. Nodos totales:', Object.keys(dic).length);
