const fs = require('fs');
const dicPath = 'F:/trincado/public/data/diccionario_sinapsis.json';
let dic = JSON.parse(fs.readFileSync(dicPath, 'utf8'));

// BLOQUE 1: Términos fundamentales del sistema doctrinal
Object.assign(dic, {
  "Ley de Amor": { "Definición": "La Ley Única que rige el universo. Es la ley madre de la que se derivan todas las demás (Afinidad, Justicia, Igualdad, Compensación). No es un sentimiento — es la fuerza estructural del Universo.", "Conexiones": ["Leyes Fatales","Ley Madre","Ama a tu Hermano","Hellí"], "Obras": ["Los Extremos se Tocan","Código de Amor Universal","Los Cinco Amores"] },
  "Ley Madre": { "Definición": "Nombre que recibe la Ley de Amor por ser la fuente de todas las leyes fatales. Todo lo que no emana de ella es norma humana provisional.", "Conexiones": ["Ley de Amor","Leyes Fatales"], "Obras": ["Los Extremos se Tocan"] },
  "Ama a tu Hermano": { "Definición": "El mandato único del Padre, enunciado por Shet hace 57 siglos, repetido por Jesús, base de toda la doctrina de Trincado. No es un consejo — es la Ley.", "Conexiones": ["Ley de Amor","Shet","Sánscrito","Mandato Único"], "Obras": ["Los Extremos se Tocan","Código de Amor Universal","Buscando a Dios"] },
  "Mandato Único": { "Definición": "El Mandato de Amor: 'Ama a tu hermano'. Todo lo demás en la doctrina es explicación, demostración o aplicación de este mandato.", "Conexiones": ["Ama a tu Hermano","Ley de Amor","Shet"], "Obras": ["Los Extremos se Tocan"] },
  "Shet": { "Definición": "El Primer Instructor de la humanidad, autor del Sánscrito. Estableció hace 57 siglos el axioma: 'Los hombres todos son hermanos'. Es el tronco de toda la sabiduría que luego se fragmentó en las escuelas de Oriente.", "Conexiones": ["Sánscrito","57 Siglos","Adán","Familia Misionera"], "Obras": ["Los Extremos se Tocan","Filosofía Austera Racional"] },
  "Sánscrito": { "Definición": "La primera escritura racional de la humanidad, creada por Shet. No es solo un idioma — es la doctrina de la verdad codificada. Raíz de la que derivan el Vedanta, el Veda y todas las grandes tradiciones espirituales antes de su adulteración.", "Conexiones": ["Shet","57 Siglos","Primera Escritura Racional","Continuidad Doctrinal"], "Obras": ["Los Extremos se Tocan","Filosofía Austera Racional"] },
  "57 Siglos": { "Definición": "La antigüedad del Sánscrito de Shet: 5700 años. Establece que la doctrina racional precede en milenios a todas las religiones institucionalizadas.", "Conexiones": ["Shet","Sánscrito","Historia Misionera"], "Obras": ["Los Extremos se Tocan","Filosofía Austera Racional"] },
  "Leyes Fatales": { "Definición": "Las cuatro leyes que se derivan de la Ley de Amor: Afinidad, Justicia, Igualdad y Compensación. Son fatales porque operan por necesidad — no pueden ser suspendidas por ningún poder humano o religioso.", "Conexiones": ["Afinidad","Justicia","Igualdad","Compensación","Ley de Amor"], "Obras": ["Los Extremos se Tocan","Código de Amor Universal"] },
  "Afinidad": { "Definición": "Primera ley fatal: los semejantes se atraen. Opera en lo físico (magnetismo), en lo social (comunidades) y en lo espiritual (karma de atracción). Explica por qué cada espíritu atrae las situaciones que corresponden a su nivel.", "Conexiones": ["Leyes Fatales","Ley de Amor","Magnetismo Espiritual"], "Obras": ["Los Extremos se Tocan","Código de Amor Universal"] },
  "Justicia": { "Definición": "Segunda ley fatal: cada acto tiene su consecuencia exacta. No es venganza — es la contabilidad perfecta del Universo. La justicia de la Escuela no castiga: corrige.", "Conexiones": ["Leyes Fatales","Compensación","Liquidación de Cuentas"], "Obras": ["Los Extremos se Tocan","Código de Amor Universal"] },
  "Igualdad": { "Definición": "Tercera ley fatal: todos los espíritus son iguales en origen. Las diferencias son de grado evolutivo, no de valor intrínseco. Ninguna raza, nación o clase es superior en esencia.", "Conexiones": ["Leyes Fatales","Igualdad Espiritual","Cruce de Razas"], "Obras": ["Los Extremos se Tocan","Los Cinco Amores"] },
  "Compensación": { "Definición": "Cuarta ley fatal: la contabilidad exacta del Universo. Lo que se da se recibe; lo que se toma sin derecho, se devuelve con intereses. No es karma místico — es la ecuación que el Universo siempre equilibra.", "Conexiones": ["Leyes Fatales","Justicia","Liquidación de Cuentas"], "Obras": ["Los Extremos se Tocan","Código de Amor Universal"] },
  "Liquidación de Cuentas": { "Definición": "El proceso histórico y espiritual por el que la Ley de Justicia cobra las deudas acumuladas. No es un fin del mundo — es el balance periódico que abre nuevos ciclos.", "Conexiones": ["Compensación","Justicia","Ley de Justicia","Profilaxis de la Vida"], "Obras": ["Profilaxis de la Vida","Los Extremos se Tocan"] },
  "Extremos del Error": { "Definición": "Las desviaciones opuestas a la Ley que inevitablemente colisionan y se destruyen. El capitalismo salvaje y el comunismo ateo son extremos; ambos chocarán porque ninguno es la Ley.", "Conexiones": ["Polos de la Ley","Ley de Compensación","Primera Guerra Mundial"], "Obras": ["Los Extremos se Tocan"] },
  "Polos de la Ley": { "Definición": "Los extremos legítimos de la Ley — el bien y el bien mayor. Son complementarios, no contradictorios. No confundir con los Extremos del Error, que son desviaciones fuera de la Ley.", "Conexiones": ["Extremos del Error","Ley de Amor","Dos Polos"], "Obras": ["Los Extremos se Tocan"] }
});

fs.writeFileSync(dicPath, JSON.stringify(dic, null, 2), 'utf8');
console.log('Bloque 1 completado. Nodos totales:', Object.keys(dic).length);
