const fs = require('fs');
const dicPath = 'F:/trincado/public/data/diccionario_sinapsis.json';
let dic = JSON.parse(fs.readFileSync(dicPath, 'utf8'));

// BLOQUE 4: Espíritu, alma, conciencia y estructura psico-espiritual (Filosofía Austera Racional)
Object.assign(dic, {
  "Espíritu": { "Definición": "El único ser consciente e individual. El alma no es el espíritu — es la colección de instintos animales acumulados en la evolución. El espíritu es el agente racional que usa el cuerpo como instrumento y el alma como reserva de experiencias.", "Conexiones": ["Alma","Conciencia","Instrumento Físico","Poder Moderador"], "Obras": ["Filosofía Austera Racional","El Magnetismo en su Origen"] },
  "Alma": { "Definición": "No es el ser espiritual individual — es la colección de instintos de todos los reinos (mineral, vegetal, animal) acumulados en millones de años de evolución. El espíritu la gobierna; no son lo mismo. Confundirlos es el error base de todas las religiones.", "Conexiones": ["Espíritu","Instintos","Filosofía Austera Racional"], "Obras": ["Filosofía Austera Racional"] },
  "Poder Moderador": { "Definición": "La facultad del espíritu de inhibir los impulsos del alma y el cuerpo. Demuestra que el espíritu es el soberano — no el esclavo — de su instrumento biológico. Sin poder moderador, el hombre opera como animal.", "Conexiones": ["Espíritu","Discernimiento","Voluntad Dirigida"], "Obras": ["Filosofía Austera Racional"] },
  "Discernimiento": { "Definición": "El termómetro del progreso espiritual. El discernimiento es el juicio de conciencia que revela, sin error, cuánto ha evolucionado un espíritu. Dime cuánto discernimiento tienes y te diré cuán cerca estás de la Ley.", "Conexiones": ["Espíritu","Poder Moderador","Grados Espirituales"], "Obras": ["Filosofía Austera Racional"] },
  "Voluntad": { "Definición": "La acción del espíritu en el mundo. No es un impulso ciego — es el resultado de un proceso deliberativo interno: un 'plebiscito' entre motivos. La voluntad libre requiere discernimiento; sin él, es solo deseo disfrazado.", "Conexiones": ["Poder Moderador","Discernimiento","Espíritu","Voluntad Dirigida"], "Obras": ["Filosofía Austera Racional"] },
  "Voluntad Dirigida": { "Definición": "La voluntad que opera bajo el discernimiento del espíritu. Opuesta a la voluntad ciega del impulso animal. En el Método Supremo, la voluntad dirigida es la herramienta principal del magnetizador.", "Conexiones": ["Voluntad","Discernimiento","Método Supremo","Sugestión"], "Obras": ["Filosofía Austera Racional","El Magnetismo en su Origen"] },
  "Grados Espirituales": { "Definición": "Los niveles de evolución del espíritu medidos por su grado de discernimiento, amor y dominio sobre el alma. No hay saltos — el progreso es gradual y acumulativo. Los grados del Método Supremo reflejan estos grados espirituales.", "Conexiones": ["Discernimiento","7 Grados","Espíritu","Método Supremo"], "Obras": ["Filosofía Austera Racional","El Magnetismo en su Origen"] },
  "Instrumento Físico": { "Definición": "El cuerpo humano como instrumento del espíritu — no el espíritu mismo. El cerebro es el micrófono que reproduce la vibración del espíritu, no el generador del pensamiento. El cuerpo requiere mantenimiento (incluyendo el amor de la carne) para servir bien.", "Conexiones": ["Espíritu","Cerebro Micrófono","Amor de la Carne","Instrumento del Espíritu"], "Obras": ["Filosofía Austera Racional","El Magnetismo en su Origen"] },
  "Instrumento del Espíritu": { "Definición": "El concepto de que el cuerpo físico es el instrumento que el espíritu usa para operar en el plano material. Como cualquier instrumento, requiere calibración, mantenimiento y respeto.", "Conexiones": ["Instrumento Físico","Espíritu","Aseo","Serenidad"], "Obras": ["El Magnetismo en su Origen","Filosofía Austera Racional"] },
  "Desdoblamiento": { "Definición": "La capacidad del espíritu de operar más allá de los límites del cuerpo físico. No es proyección astral mística — es la demostración experimental de que el espíritu no está contenido en la materia sino que la usa como punto de apoyo.", "Conexiones": ["Método Supremo","7 Grados","Sonambulismo","Instrumento Físico"], "Obras": ["El Magnetismo en su Origen"] },
  "Sonambulismo Clarividente": { "Definición": "El Grado Sexto del Método Supremo: el punto en que la materia alcanza su máxima fuerza magnética permitiendo el sonambulismo y la clarividencia. No es fenómeno paranormal — es el resultado del desarrollo metódico del magnetismo.", "Conexiones": ["Desdoblamiento","7 Grados","Método Supremo"], "Obras": ["El Magnetismo en su Origen"] },
  "Mediumidad": { "Definición": "La capacidad de servir como canal de comunicación entre el plano espiritual y el material. Para Trincado, no es un don especial sino una facultad que todos tienen en grado diverso y que puede desarrollarse con el Método.", "Conexiones": ["Desdoblamiento","Método Supremo","Posesión"], "Obras": ["El Magnetismo en su Origen","Ley de las Mediumidades"] },
  "Mirada Magnética": { "Definición": "La expresión más directa del magnetismo personal. No es 'fascinación' ni 'alucinación' — es la transmisión de voluntad espiritual a través del canal visual. Una de las instrucciones prácticas del Método Supremo.", "Conexiones": ["Método Supremo","Magnetismo Práctico","Voluntad Dirigida"], "Obras": ["El Magnetismo en su Origen"] },
  "Serenidad": { "Definición": "La condición base para el trabajo magnético y espiritual. Sin serenidad, el magnetismo se dispersa y la voluntad no puede dirigirse. Es la instrucción final del Método Supremo porque sin ella todas las demás son inútiles.", "Conexiones": ["Método Supremo","Instrumento del Espíritu","Poder Moderador"], "Obras": ["El Magnetismo en su Origen"] },
  "Sugestión": { "Definición": "La herramienta de la voluntad dirigida: sugestionar es dirigir la propia voluntad y la de otros hacia un objetivo definido. No es manipulación — es el ejercicio consciente del magnetismo interpersonal.", "Conexiones": ["Mirada Magnética","Voluntad Dirigida","Método Supremo"], "Obras": ["El Magnetismo en su Origen"] },
  "Querer es Poder": { "Definición": "Un axioma verdadero pero incompleto: querer es poder solo dentro del grado de desarrollo actual. El querer sin el grado correspondiente produce frustración, no resultado. El Método da el grado; la voluntad da la dirección.", "Conexiones": ["Sugestión","Grados Espirituales","Método Supremo","Voluntad"], "Obras": ["El Magnetismo en su Origen"] },
  "Amor de la Carne": { "Definición": "El mandato de la naturaleza para la perpetuación y el equilibrio biológico-espiritual. No es pecado — es mandato de ley divina. Negarle al cuerpo este derecho por supuesta 'pureza' es desconocer que el cuerpo es el instrumento del espíritu y necesita su mantenimiento.", "Conexiones": ["Anti-Celibato","Instrumento Físico","Equilibrio Natural","Mujer como Arca Santa"], "Obras": ["El Magnetismo en su Origen","Profilaxis de la Vida","Los Cinco Amores"] },
  "Anti-Celibato": { "Definición": "La postura doctrinal contra el celibato religioso impuesto. No como apología del libertinaje sino como defensa del equilibrio natural: el cuerpo necesita el amor de la carne; suprimirlo crea desequilibrio espiritual, no pureza.", "Conexiones": ["Amor de la Carne","Equilibrio Natural","Ramera","Mujer como Arca Santa"], "Obras": ["El Magnetismo en su Origen","Profilaxis de la Vida"] },
  "Mujer como Arca Santa": { "Definición": "La definición de la mujer en la doctrina: no es un ser secundario ni la 'tentación' religiosa. Es el Arca Santa de la Creación — el recipiente sagrado donde el espíritu toma forma nueva. Su respeto no es opcional: es ley.", "Conexiones": ["Anti-Celibato","Amor de la Carne","Los Cinco Amores","Profilaxis de la Vida"], "Obras": ["Profilaxis de la Vida","Los Cinco Amores"] },
  "Equilibrio Natural": { "Definición": "El estado de armonía que el organismo físico y espiritual requiere para operar correctamente. Cualquier supresión artificial (celibato, ayuno extremo, mortificación) rompe este equilibrio y daña el instrumento del espíritu.", "Conexiones": ["Amor de la Carne","Instrumento Físico","Profilaxis de la Vida"], "Obras": ["El Magnetismo en su Origen","Profilaxis de la Vida"] },
  "Necesidad del Cuerpo": { "Definición": "El principio de que las necesidades físicas del cuerpo (alimentación, amor, descanso, movimiento) son mandatos de la ley natural — no debilidades morales. Ignorarlas es dañar el instrumento que el espíritu necesita.", "Conexiones": ["Instrumento Físico","Equilibrio Natural","Amor de la Carne"], "Obras": ["El Magnetismo en su Origen","Profilaxis de la Vida"] }
});

fs.writeFileSync(dicPath, JSON.stringify(dic, null, 2), 'utf8');
console.log('Bloque 4 completado. Nodos totales:', Object.keys(dic).length);
