const fs = require('fs');
const dicPath = 'F:/trincado/public/data/diccionario_sinapsis.json';
let dic = JSON.parse(fs.readFileSync(dicPath, 'utf8'));

// BLOQUE 5: Familia, identidades históricas, ciencia, y términos restantes
Object.assign(dic, {
  "Adán": { "Definición": "No el primer hombre biológico — el primer iniciado de la Escuela de Shet, el primer receptor consciente del mandato racional. Con Adán comienza la historia doctrinal de la humanidad, no la biológica. La Raza Adámica es la raza que porta la ley del amor.", "Conexiones": ["Shet","Eva","Familia Misionera","Anti-Pecado Original"], "Obras": ["Los Extremos se Tocan","Filosofía Austera Racional"] },
  "Eva": { "Definición": "La compañera misionera de Adán — la primera mujer en recibir el mandato racional junto a él. No es la 'culpable del pecado original' — esa es la adulteración religiosa. Eva es la primera Arca Santa en cumplir su función consciente.", "Conexiones": ["Adán","Familia Misionera","Mujer como Arca Santa","Anti-Pecado Original"], "Obras": ["Los Extremos se Tocan","Los Cinco Amores"] },
  "Anti-Pecado Original": { "Definición": "La negación doctrinal del pecado original como realidad espiritual. No existe pecado heredado — existe ignorancia que la Escuela viene a corregir. Cada espíritu nace limpio; lo que acumula es de su propia cuenta en esta y otras vidas.", "Conexiones": ["Adán","Eva","Ley de Justicia","Igualdad Espiritual"], "Obras": ["Los Extremos se Tocan","Filosofía Austera Racional"] },
  "Familia Misionera": { "Definición": "La familia de Adán y Eva como unidad misionera: su propósito no era solo procrear sino sembrar la ley del amor en la tierra. Cada familia que vive bajo la ley es una célula misionera de la Escuela.", "Conexiones": ["Adán","Eva","Shet","Sánscrito"], "Obras": ["Los Extremos se Tocan"] },
  "Continuidad Misionera": { "Definición": "El principio de que la misión doctrinal es continua a través de los siglos y las encarnaciones. Shet, Jesús, Trincado-Jaime son eslabones de la misma cadena. La Escuela es la institución que garantiza esa continuidad.", "Conexiones": ["Jaime","Shet","Jesús Histórico","Escuela Magnetológica"], "Obras": ["Buscando a Dios","Los Extremos se Tocan"] },
  "Continuidad de la Escuela": { "Definición": "La Escuela Magnetológica existe desde Shet aunque haya cambiado de nombre y de forma. Su continuidad no depende de instituciones sino de espíritus que preservan y transmiten la verdad en cada época.", "Conexiones": ["Continuidad Misionera","Escuela Magnetológica","Shet","Jaime"], "Obras": ["Los Extremos se Tocan","Código de Amor Universal"] },
  "Historia Misionera": { "Definición": "La lectura de la historia como sucesión de misiones espirituales: Shet-Adán, Moisés, Jesús, Trincado. Cada misión trae la misma verdad adaptada al momento histórico. Cada vez que la verdad es adulterada, aparece una nueva misión.", "Conexiones": ["Continuidad Misionera","Adulteración Histórica","Constantino","Shet"], "Obras": ["Los Extremos se Tocan"] },
  "Gamaliel": { "Definición": "La escuela rabínica en Jerusalem donde Jesús fue formado. No fue un carpintero ignorante — fue un estudiante de la más alta escuela de su época. Esto explica la profundidad de su enseñanza y su capacidad para debatir con los doctores del Templo.", "Conexiones": ["Jesús Histórico","4 de Diciembre","Esenios"], "Obras": ["Buscando a Dios"] },
  "Esenios": { "Definición": "La comunidad esenia de la que formó parte Jesús — una fraternidad de vida austera, estudio racional y comunidad de bienes. En los esenios se encontraba ya el germen de lo que Trincado sistematizó en la Escuela.", "Conexiones": ["Jesús Histórico","Gamaliel","Continuidad Misionera"], "Obras": ["Buscando a Dios"] },
  "4 de Diciembre": { "Definición": "La fecha real del nacimiento de Jesús de Nazaret, según la doctrina. El 25 de diciembre es el solsticio solar pagano que Roma adoptó para la liturgia cristiana. La Escuela preserva la fecha real contra la mixtificación.", "Conexiones": ["Jesús Histórico","Gamaliel","Anti-Deificación"], "Obras": ["Buscando a Dios"] },
  "Anti-Deificación": { "Definición": "La postura doctrinal de restituir la humanidad de Jesús contra la deificación que Roma le impuso en Nicea (325 d.C.). Jesús no es Dios — es el Misionero más importante del segundo ciclo doctrinal. Deificarlo fue la operación de poder de Constantino.", "Conexiones": ["Jesús Histórico","Constantino","Traición a Jesús","Anti-Cristo Dios"], "Obras": ["Buscando a Dios"] },
  "Anti-Cristo Dios": { "Definición": "El rechazo doctrinal al 'Cristo' como ser divino. 'Cristo' no es el nombre de Jesús — es un título griego (ungido) que la iglesia usó para construir su teología. El Cristo-dios es la mixtificación; Jesús de Nazaret, hombre y misionero, es la verdad.", "Conexiones": ["Anti-Deificación","Jesús Histórico","Traición a Jesús"], "Obras": ["Buscando a Dios"] },
  "Origen de las Religiones": { "Definición": "Para Trincado, todas las religiones derivan de la adulteración del tronco original de Shet. Cada civilización tomó fragmentos de esa verdad, los mezcló con sus intereses de poder, y construyó su sistema religioso. Ninguna es la fuente — todas son derivaciones adulteradas.", "Conexiones": ["Shet","Adulteración Histórica","Concupiscencia Religiosa","Ramera"], "Obras": ["Los Extremos se Tocan","Primer Rayo de Luz"] },
  "Concupiscencia Religiosa": { "Definición": "El término técnico de Trincado para describir la naturaleza de las religiones: un conjunto de pasiones humanas (miedo, deseo de poder, codicia) elevadas a sistema y simbolizadas en un ente o artefacto que concentra la devoción.", "Conexiones": ["Ramera","Origen de las Religiones","Anti-Religión","Dominio del Dogma"], "Obras": ["El Magnetismo en su Origen","Los Extremos se Tocan"] },
  "Anti-Religión": { "Definición": "La postura de Trincado no es ateísmo ni anticlericalismo emocional. Es la negación de la religión como institución intermediaria entre el hombre y el Padre. La relación con Hellí es directa, sin sacerdotes, sin rituales, sin templos.", "Conexiones": ["Hellí","Concupiscencia Religiosa","Enseñanza Racional","Anti-Dogma"], "Obras": ["Buscando a Dios","Primer Rayo de Luz"] },
  "Dominio del Dogma": { "Definición": "El período histórico — desde Constantino hasta el siglo XX — en que el dogma religioso fue el principal instrumento de control social. Las guerras de religión, la Inquisición y los estados confesionales son sus expresiones.", "Conexiones": ["Papado","Ramera","Adulteración Histórica","Bestia 666"], "Obras": ["Los Extremos se Tocan","Primer Rayo de Luz"] },
  "Apocalipsis Racional": { "Definición": "La lectura de los textos apocalípticos (especialmente el de Juan) como diagnóstico histórico codificado, no como profecía literal del fin del mundo. El 666, la Ramera, la Bestia son identificaciones de realidades históricas concretas.", "Conexiones": ["Bestia 666","Ramera de Babilonia","Dominio del Dogma"], "Obras": ["Buscando a Dios","Primer Rayo de Luz"] },
  "Fomentar el Error": { "Definición": "El acto de mantener activamente la ignorancia y el error en otros para beneficiarse de ello. Para Trincado, esto es la definición de culpabilidad real. No el que yerra, sino el que sabe la verdad y la oculta por negocio.", "Conexiones": ["Culpables del Error","Ramera","Dominio del Dogma"], "Obras": ["Los Extremos se Tocan"] },
  "Juicio Supremo": { "Definición": "El análisis racional que la historia pronuncia sobre las causas del desorden humano. No es el juicio bíblico del fin de los tiempos — es el veredicto de la Ley sobre los errores acumulados, pronunciado a través de los eventos históricos.", "Conexiones": ["Causas de la Guerra","Culpables del Error","Ley de Justicia","Liquidación"], "Obras": ["Los Extremos se Tocan"] },
  "Liquidación": { "Definición": "El proceso por el que la Ley de Justicia salda las deudas acumuladas — históricas, sociales y espirituales. No es castigo divino — es la ecuación del Universo que siempre se equilibra, tarde o temprano.", "Conexiones": ["Liquidación de Cuentas","Compensación","Justicia","Juicio Supremo"], "Obras": ["Los Extremos se Tocan","Profilaxis de la Vida"] },
  "Diagnóstico Doctrinal": { "Definición": "El método de Trincado: antes de prescribir, diagnosticar. La Escuela no propone soluciones sin antes identificar con precisión las causas del problema. El diagnóstico doctrinal es clínico, no emotivo.", "Conexiones": ["Juicio Supremo","Causas de la Guerra","Escalpelo de la Razón"], "Obras": ["Los Extremos se Tocan"] },
  "Diagnóstico Final": { "Definición": "El veredicto conclusivo del Cap. 38 de 'Los Extremos se Tocan': las religiones, al mezclar lo espiritual con la concupiscencia institucional, son el motor del desorden mundial. La Escuela es la alternativa.", "Conexiones": ["Diagnóstico Doctrinal","Concupiscencia Religiosa","Juicio Supremo"], "Obras": ["Los Extremos se Tocan"] },
  "Escalpelo de la Razón": { "Definición": "La metáfora que Trincado usa para su propio método: cortar el error con precisión quirúrgica, sin anestesia, sin piedad con la mentira. No porque disfrute del dolor, sino porque la salud del espíritu lo requiere.", "Conexiones": ["Diagnóstico Doctrinal","Juicio Supremo","Filosofía Austera Racional"], "Obras": ["Los Extremos se Tocan"] }
});

fs.writeFileSync(dicPath, JSON.stringify(dic, null, 2), 'utf8');
console.log('Bloque 5 completado. Nodos totales:', Object.keys(dic).length);
