const fs = require('fs');
const dicPath = 'F:/trincado/public/data/diccionario_sinapsis.json';
let dic = JSON.parse(fs.readFileSync(dicPath, 'utf8'));

// BLOQUE 3: Términos de la estructura social, política y económica de la Doctrina
Object.assign(dic, {
  "Comuna Universal": { "Definición": "La organización social que corresponde a la Ley de Amor: basada en el trabajo de todos, la propiedad de Eloí, y la distribución justa. No es utopía — es la aplicación social de las leyes fatales. Cada habitante trabaja, cada habitante recibe según su aporte.", "Conexiones": ["Eloí","Mundo Comunizado","Cuerpo Ideal Social","Código de Amor Universal"], "Obras": ["Los Extremos se Tocan","Código de Amor Universal"] },
  "Cuerpo Ideal Social": { "Definición": "La descripción concreta de la sociedad del Día del Amor: el hombre que trabaja, la mujer que educa, el niño que aprende, el anciano que guía. Cada rol sostenido en la ley, no en el poder. Es la realización práctica de la Ley de Amor.", "Conexiones": ["Día del Amor","CGS","Nueva Civilización","Comuna Universal"], "Obras": ["Los Extremos se Tocan"] },
  "CGS": { "Definición": "El Código de Gobierno Social — la constitución racional de la nueva organización humana bajo la Ley de Amor. No es una constitución política convencional: es la aplicación de las leyes fatales al gobierno de los hombres.", "Conexiones": ["Cuerpo Ideal Social","Día del Amor","Código de Amor Universal"], "Obras": ["Los Extremos se Tocan"] },
  "Día del Amor": { "Definición": "El período histórico en proceso en que la humanidad aplica conscientemente la Ley de Amor. No es un evento apocalíptico sino una transición: el punto en que la mayoría actúa bajo la ley y no bajo el error.", "Conexiones": ["Cuerpo Ideal Social","CGS","Nueva Civilización","Eloí"], "Obras": ["Los Extremos se Tocan"] },
  "Nueva Civilización": { "Definición": "La civilización que emerge cuando los Extremos del Error han colisionado y la Ley ocupa su lugar. Civilización en el sentido real: conocimiento y fruición de todo lo que la tierra ofrece, distribuido equitativamente.", "Conexiones": ["Día del Amor","Cuerpo Ideal Social","Civilización Racional"], "Obras": ["Los Extremos se Tocan"] },
  "Civilización Racional": { "Definición": "La civilización cuyo fundamento es la razón y la ley, no el dogma y el poder. Para Trincado, las llamadas 'grandes civilizaciones' del pasado no fueron civilizaciones — fueron organizaciones de pillaje con decoración cultural.", "Conexiones": ["Nueva Civilización","Enseñanza Racional","Escuela Magnetológica"], "Obras": ["Los Extremos se Tocan"] },
  "Herencia Universal": { "Definición": "El principio de que todos los hombres son herederos del Universo porque Eloí es el único propietario. La pobreza es un crimen social, no un destino divino: implica que alguien tomó lo que era de todos.", "Conexiones": ["Eloí","Solo Eloí Propietario","Propiedad Universal"], "Obras": ["Los Extremos se Tocan"] },
  "Solo Eloí Propietario": { "Definición": "El axioma económico-espiritual de la doctrina: nadie puede ser propietario absoluto de la tierra porque solo Eloí lo es. La propiedad privada de los medios de vida es una usurpación — un robo a los herederos del Padre.", "Conexiones": ["Eloí","Herencia Universal","Propiedad Universal","Mundo Comunizado"], "Obras": ["Los Extremos se Tocan"] },
  "Propiedad Universal": { "Definición": "El concepto de que la tierra, los recursos naturales y los medios de producción pertenecen a Eloí y en herencia a todos sus hijos. Ningún individuo ni institución puede apropiárselos permanentemente.", "Conexiones": ["Eloí","Solo Eloí Propietario","Herencia Universal"], "Obras": ["Los Extremos se Tocan","Código de Amor Universal"] },
  "Igualdad Espiritual": { "Definición": "El principio de que todos los espíritus son iguales en origen y valor intrínseco. Las diferencias son de grado evolutivo — de progreso acumulado — no de valor esencial. Ninguna raza ni nación es superior en sustancia.", "Conexiones": ["Igualdad","Cruce de Razas","Leyes Fatales"], "Obras": ["Los Extremos se Tocan","Los Cinco Amores"] },
  "Comunismo Racional": { "Definición": "El comunismo de Trincado — distinto del marxista. No es ateísmo ni dictadura del proletariado. Es la organización social bajo la Ley de Amor donde Eloí es propietario, todos trabajan y todos heredan. Tiene raíces en los Comuneros de Castilla.", "Conexiones": ["Mundo Comunizado","Comuna Universal","Eloí","Anti-Dios Comercial"], "Obras": ["Filosofía Austera Racional","Los Extremos se Tocan"] },
  "Solidaridad Universal": { "Definición": "La interconexión de todos los seres bajo la misma ley y la misma sustancia. No es altruismo opcional — es la realidad estructural del Universo. El egoísmo es una ilusión que la Ley tarde o temprano corrige.", "Conexiones": ["Universo Solidarizado","Ley de Amor","Ama a tu Hermano"], "Obras": ["Los Extremos se Tocan","Código de Amor Universal"] },
  "Enseñanza Racional": { "Definición": "El método de la Escuela: enseñar por demostración, razonamiento y evidencia — nunca por dogma, autoridad o fe ciega. El estudiante debe poder refutar cualquier afirmación si tiene argumentos mejores.", "Conexiones": ["Escuela","Enseñanza sin Dogma","Ciudad Invisible"], "Obras": ["Los Extremos se Tocan","Código de Amor Universal"] },
  "Enseñanza sin Dogma": { "Definición": "El principio pedagógico de la Escuela: ninguna verdad se impone por autoridad. Cada proposición doctrinal debe sostenerse por su propia coherencia racional. El dogma es el enemigo del conocimiento.", "Conexiones": ["Enseñanza Racional","Anti-Dogma","Escuela"], "Obras": ["Filosofía Austera Racional","Código de Amor Universal"] },
  "Anti-Dogma": { "Definición": "La postura epistemológica de la Escuela: el dogma — la afirmación que no puede ser cuestionada — es la herramienta del poder, no del conocimiento. La doctrina de Trincado acepta ser debatida porque se sostiene en razón, no en autoridad.", "Conexiones": ["Enseñanza Racional","Filosofía Austera Racional","Ramera"], "Obras": ["Buscando a Dios","Filosofía Austera Racional"] },
  "Primera Guerra Mundial": { "Definición": "La demostración histórica de la Ley de los Extremos: la colisión del imperialismo religioso y el imperialismo político después de siglos de acumulación de error. Trincado la analiza en tiempo real en 'Los Extremos se Tocan' (1915-1916).", "Conexiones": ["Extremos del Error","Balcanes","Colisión de Extremos","Causas de la Guerra"], "Obras": ["Los Extremos se Tocan"] },
  "Balcanes": { "Definición": "La 'resistencia final' antes de la Primera Guerra Mundial. Para Trincado, los Balcanes representan el último punto de equilibrio que al romperse libera la energía acumulada de siglos de conflicto entre el imperialismo religioso y el político.", "Conexiones": ["Primera Guerra Mundial","Colisión de Extremos","Resistencia Rota"], "Obras": ["Los Extremos se Tocan"] },
  "Colisión de Extremos": { "Definición": "El momento en que dos extremos del error se tocan y se destruyen mutuamente. Este es el mecanismo histórico que la doctrina explica: los extremos no pueden coexistir indefinidamente — la Ley los hace colisionar.", "Conexiones": ["Extremos del Error","Balcanes","Primera Guerra Mundial","Ley de Compensación"], "Obras": ["Los Extremos se Tocan"] },
  "Resistencia Rota": { "Definición": "El momento en que el último equilibrio que contiene los extremos desaparece y se desencadena la colisión inevitable. En la historia del siglo XX: la crisis de los Balcanes que detonó la Primera Guerra.", "Conexiones": ["Balcanes","Colisión de Extremos","Primera Guerra Mundial"], "Obras": ["Los Extremos se Tocan"] },
  "Causas de la Guerra": { "Definición": "Para Trincado, las guerras no nacen de conflictos nacionales o económicos superficiales. Nacen del error acumulado durante siglos: la opresión religiosa, la injusticia económica y el militarismo son las raíces. Los líderes políticos son síntomas, no causas.", "Conexiones": ["Primera Guerra Mundial","Colisión de Extremos","Culpables del Error"], "Obras": ["Los Extremos se Tocan"] },
  "Culpables del Error": { "Definición": "Los que fomentan el error sabiendo que perciben beneficio de él. No es acusación para el odio — es diagnóstico para la corrección. Los culpables del desorden mundial son quienes han mantenido al pueblo en la ignorancia por negocio.", "Conexiones": ["Ramera","Papado","Causas de la Guerra","Fomentar el Error"], "Obras": ["Los Extremos se Tocan"] }
});

fs.writeFileSync(dicPath, JSON.stringify(dic, null, 2), 'utf8');
console.log('Bloque 3 completado. Nodos totales:', Object.keys(dic).length);
