
const ORDINALS = 'PRIMERO|PRIMERA|SEGUNDO|SEGUNDA|TERCERO|TERCERA|CUARTO|CUARTA|QUINTO|QUINTA|SEXTO|SEXTA|S\u00C9PTIMO|S\u00C9PTIMA|OCTAVO|OCTAVA|NOVENO|NOVENA|D\u00C9CIMO|D\u00C9CIMA|UND\u00C9CIMO|DUOD\u00C9CIMO|DECIMOPRIMERO|DECIMOSEGUNDO|DECIMOTERCERO|DECIMOCUARTO|DECIMOCUAR|DECIMOQUINTO|DECIMOSEXTO|DECIMOS\u00C9PTIMO|DECIMOSEPTIMO|DECIMOOCTAVO|DECIMOOCTAV|DECIMOCTAVO|DECIMOCTAV|DECIMONOVENO|VIG\u00C9SIMO|I|II|III|IV|V|VI|VII|VIII|IX|X|XI|XII|XIII|XIV|XV|XVI|XVII|XVIII|XIX|XX|UNO|DOS|TRES|CUATRO|CINCO|SEIS|SIETE|OCHO|NUEVE|DIEZ|ONCE|DOCE|TRECE|CATORCE|QUINCE|DIECIS\u00C9IS|DIECISEIS|DIECISIETE|DIECIOCHO|DIECINUEVE|VEINTE';
const CAP = 'CAP[\u00CDI]TULO';
const KEYWORD_PATTERNS = [
    new RegExp(`^(?:${CAP}\\s+(?:${ORDINALS}|\\d+)|(?:${ORDINALS})\\s+${CAP})`, 'i'),
];

const line = 'CAPÍTULO TREINTA';
const isMatch = KEYWORD_PATTERNS.some(p => p.test(line));
console.log('isMatch:', isMatch);
